from selenium import webdriver
import time
import os
import win32gui
import win32con
driver = webdriver.Firefox()
driver.get('http://r.zhongzhuoxin.com/')
driver.maximize_window()
driver.implicitly_wait(10)
driver.find_element_by_id('loginname').send_keys('admin')
driver.find_element_by_id('password').send_keys('adminzzx')
driver.find_element_by_id('code').send_keys('wnyzm')
time.sleep(1)
driver.find_element_by_id('to-recover').click()
time.sleep(3)
driver.find_element_by_css_selector('#sidebar-collapse > i').click()
driver.find_element_by_css_selector('#lm24 > a > span').click()
time.sleep(1)
driver.find_element_by_css_selector('#z28 > a').click()
driver.switch_to.frame(driver.find_element_by_id('mainFrame'))
driver.switch_to.frame(driver.find_element_by_id('page_z28'))
driver.find_element_by_css_selector('.btn.btn-small.btn-success').click()
driver.switch_to.default_content()
driver.switch_to.frame(driver.find_element_by_id('_DialogFrame_0'))
title = u'测试H5'
driver.find_element_by_css_selector('#TITLE').send_keys(title)
driver.find_element_by_id('datetimepicker1').click()
# driver.find_element_by_css_selector('.hour.active').click()
driver.find_element_by_css_selector('.table-condensed > tbody > tr > td > span:nth-child(24)').click()
driver.find_element_by_css_selector('.table-condensed > tbody > tr > td > span:nth-child(12)').click()
driver.switch_to.default_content()
#切换h5正文输入框iframe
driver.switch_to.frame(driver.find_element_by_id('_DialogFrame_0'))
driver.switch_to.frame(driver.find_element_by_id('ueditor_0'))
driver.find_element_by_css_selector('.view > body.view').send_keys('自动创建H5')
driver.switch_to.default_content()
driver.switch_to.frame(driver.find_element_by_id('_DialogFrame_0'))
driver.find_element_by_xpath(".//*[@id='table_report']/tbody/tr[2]/td/a[1]").click()
driver.find_element_by_css_selector('#myDropzone > div').click()
time.sleep(3)
# os.system('D:\\AutoIt\\AutoIt3\\uploadh5.exe')
dialog = win32gui.FindWindow('#32770',u'打开')
ComboBoxEx32 = win32gui.FindWindowEx(dialog, 0, 'ComboBoxEx32', None)
ComboBox = win32gui.FindWindowEx(ComboBoxEx32, 0, 'ComboBox', None)
Edit = win32gui.FindWindowEx(dialog,0,'Edit',None)
button = win32gui.FindWindowEx(Edit,0,'button',None)
win32gui.SendMessage(Edit,win32con.WM_SETTEXT,None,'f:\\c.jpg')
win32gui.SendMessage(dialog,win32con.WM_COMMAND,1,button)
time.sleep(5)
driver.find_element_by_css_selector('#table_report > tbody > tr:nth-child(6) > td > a:nth-child(1)').click()
driver.switch_to.default_content()
driver.switch_to.frame(driver.find_element_by_id('mainFrame'))
driver.switch_to.frame(driver.find_element_by_id('page_z28'))
text = driver.find_element_by_css_selector('#table_report > tbody > tr:nth-child(1) > td:nth-child(4)').text
print(text)
if title in text:
    print('H5创建成功')
else:
    print('H5创建失败')
time.sleep(2)
driver.quit()